apiVersion: apps/v1
kind: Deployment
metadata:
  name: traced-fastapi
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traced-fastapi
  template:
    metadata:
      labels:
        app: traced-fastapi
    spec:
      containers:
        - name: traced-fastapi
          image: tapan2609/traced-fastapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # Point OTEL exporter to collector service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.otel.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_SERVICE_NAME
              value: "traced-fastapi-service"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: traced-fastapi
  namespace: demo
spec:
  selector:
    app: traced-fastapi
  ports:
    - port: 80
      targetPort: 8000

